import { escapeHtml, money } from "./format";
import type { InvoicePdfData } from "./types";

export function renderClassicTemplate(data: InvoicePdfData): string {
  const itemRows = data.items.map((item) => `<tr><td>${escapeHtml(item.description)}</td><td>${escapeHtml(item.quantity)}</td><td>${money(item.unit_price_cents, data.invoice.currency)}</td><td>${money(item.total_cents, data.invoice.currency)}</td></tr>`).join("");
  const logo = data.org.logo_url ? `<img src="${escapeHtml(data.org.logo_url)}" alt="${escapeHtml(data.org.name)}" class="logo">` : `<strong class="org-name">${escapeHtml(data.org.name)}</strong>`;
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    :root{--accent:${escapeHtml(data.org.brand_color)};--ink:#17202a;--muted:#64748b}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:var(--ink);margin:0;padding:46px;font-size:12px}.header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid var(--accent);padding-bottom:22px}.logo{max-width:150px;max-height:54px}.org-name{font-size:22px}.title{text-align:right}.title h1{font-size:26px;margin:0 0 6px;color:var(--accent)}.muted{color:var(--muted)}.details{display:grid;grid-template-columns:2fr 1fr 1fr;gap:24px;padding:24px 0}.label{font-size:10px;font-weight:bold;letter-spacing:.08em;color:var(--muted);text-transform:uppercase;margin-bottom:7px}table{width:100%;border-collapse:collapse;margin-top:8px}th{background:#f1f5f9;color:#334155;font-size:10px;text-align:left;text-transform:uppercase;padding:10px}td{border-bottom:1px solid #e2e8f0;padding:11px 10px}th:not(:first-child),td:not(:first-child){text-align:right}.summary{margin:22px 0 0 auto;width:260px}.summary div{display:flex;justify-content:space-between;padding:5px 0}.total{border-top:2px solid var(--accent);font-size:15px;font-weight:bold;margin-top:7px;padding-top:10px!important}.notes{border-top:1px solid #e2e8f0;margin-top:30px;padding-top:16px}.notes p{white-space:pre-wrap}
  </style></head><body><header class="header"><div>${logo}<div class="muted">${escapeHtml(data.org.address)}</div></div><div class="title"><h1>INVOICE</h1><div>#${escapeHtml(data.invoice.number)}</div></div></header><section class="details"><div><div class="label">Bill to</div><strong>${escapeHtml(data.client.name)}</strong><div>${escapeHtml(data.client.company_name)}</div><div class="muted">${escapeHtml(data.client.email)}</div></div><div><div class="label">Issue date</div>${escapeHtml(data.invoice.issue_date)}</div><div><div class="label">Due date</div>${escapeHtml(data.invoice.due_date)}</div></section><table><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody>${itemRows}</tbody></table><section class="summary"><div><span>Subtotal</span><span>${money(data.totals.subtotal_cents, data.invoice.currency)}</span></div>${data.totals.discount_cents ? `<div><span>Discount</span><span>-${money(data.totals.discount_cents, data.invoice.currency)}</span></div>` : ""}${data.totals.tax_cents ? `<div><span>Tax</span><span>${money(data.totals.tax_cents, data.invoice.currency)}</span></div>` : ""}<div class="total"><span>Total</span><span>${money(data.totals.grand_total_cents, data.invoice.currency)}</span></div></section>${data.invoice.notes ? `<section class="notes"><div class="label">Notes</div><p>${escapeHtml(data.invoice.notes)}</p></section>` : ""}</body></html>`;
}
